
DBM_AllSavedOptions = {
	["Default"] = {
		["HUDTextureOverride"] = false,
		["DontShowFarWarnings"] = true,
		["ChosenVoicePack"] = "None",
		["DontShowHudMap2"] = false,
		["AlwaysPlayVoice"] = false,
		["ShowSWarningsInChat"] = true,
		["RangeFrameRadarY"] = -100,
		["HUDAlpha1"] = 0.5,
		["StatusEnabled"] = true,
		["InfoFrameX"] = 75,
		["DontShowNameplateIcons"] = false,
		["RangeFrameX"] = 50,
		["AlwaysShowSpeedKillTimer"] = true,
		["RangeFrameY"] = -50,
		["FilterSayAndYell"] = false,
		["EnableModels"] = true,
		["SpecialWarningFlashAlph3"] = 0.4,
		["ArrowPoint"] = "TOP",
		["SWarnNameInNote"] = true,
		["FakeBWVersion"] = false,
		["InfoFramePoint"] = "CENTER",
		["CRT_Enabled"] = false,
		["SpecialWarningFlashCol2"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["WarningAlphabetical"] = true,
		["WarningFont"] = "Fonts\\FRIZQT__.TTF",
		["CheckGear"] = true,
		["SpecialWarningX"] = 0,
		["WorldBossAlert"] = false,
		["HUDSize3"] = 5,
		["DontShowPT2"] = false,
		["MCMessageShown"] = false,
		["DontShowSpecialWarnings"] = false,
		["ShowMinimapButton"] = false,
		["MoviesSeen"] = {
			["7201"] = true,
		},
		["ShowQueuePop"] = true,
		["ShowAllVersions"] = true,
		["DebugMode"] = false,
		["ShowWarningsInChat"] = true,
		["SpecialWarningFontCol"] = {
			1, -- [1]
			0.7, -- [2]
			0, -- [3]
		},
		["WarningFontStyle"] = "None",
		["InfoFrameY"] = -75,
		["ChatFrame"] = "DEFAULT_CHAT_FRAME",
		["WarningIconRight"] = true,
		["UseSoundChannel"] = "Master",
		["ShowCountdownText"] = false,
		["ShowRespawn"] = true,
		["HideQuestTooltips"] = true,
		["HUDSize2"] = 5,
		["FilterDispel"] = true,
		["DebugLevel"] = 1,
		["LFDEnhance"] = true,
		["SpecialWarningFlashDura1"] = 0.4,
		["DontShowPTNoID"] = false,
		["HideGarrisonToasts"] = true,
		["RangeFramePoint"] = "CENTER",
		["SpecialWarningFontShadow"] = false,
		["RLReadyCheckSound"] = true,
		["WOTLKTWMessageShown"] = false,
		["HideObjectivesFrame"] = true,
		["SpecialWarningFlashCol1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["DontShowPTText"] = false,
		["SpecialWarningFontSize2"] = 40,
		["SpecialWarningFlashCol5"] = {
			0.2, -- [1]
			1, -- [2]
			1, -- [3]
		},
		["HelpMessageVersion"] = 3,
		["DontShowHealthFrame"] = false,
		["AFKHealthWarning"] = false,
		["ForumsMessageShown"] = 15639,
		["AutoReplySound"] = true,
		["PTCountThreshold"] = 5,
		["AlwaysShowHealthFrame"] = false,
		["ArrowPosY"] = -150,
		["SpecialWarningSound"] = "Sound\\Spells\\PVPFlagTaken.ogg",
		["NewsMessageShown"] = 8,
		["DontShowPTCountdownText"] = false,
		["SpecialWarningSound3"] = "Sound\\Creature\\KilJaeden\\KILJAEDEN02.ogg",
		["HUDSizeOverride"] = false,
		["ShowGuildMessages"] = true,
		["CountdownVoice2"] = "Kolt",
		["AutoAcceptGuildInvite"] = false,
		["HealthFrameLocked"] = false,
		["ArrowPosX"] = 0,
		["HUDColor1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["AITimer"] = true,
		["SpecialWarningFlashDura3"] = 1,
		["MovieFilter"] = "AfterFirst",
		["HPFramePoint"] = "CENTER",
		["SpecialWarningFlashDura5"] = 1,
		["SpecialWarningSound4"] = "Sound\\Creature\\HoodWolf\\HoodWolfTransformPlayer01.ogg",
		["DontRestoreIcons"] = false,
		["HUDColor4"] = {
			0, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["DisableSFX"] = false,
		["AutologBosses"] = false,
		["SpecialWarningFlashDura4"] = 0.7,
		["SpecialWarningFlashCol3"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["SpecialWarningFlashRepeat1"] = false,
		["HUDSize4"] = 5,
		["WarningColors"] = {
			{
				["r"] = 0.41,
				["g"] = 0.8,
				["b"] = 0.94,
			}, -- [1]
			{
				["r"] = 0.95,
				["g"] = 0.95,
				["b"] = 0,
			}, -- [2]
			{
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			}, -- [3]
			{
				["r"] = 1,
				["g"] = 0.1,
				["b"] = 0.1,
			}, -- [4]
		},
		["AdvancedAutologBosses"] = false,
		["SWarningAlphabetical"] = true,
		["HUDAlpha4"] = 0.5,
		["BlockNoteShare"] = false,
		["HUDTexture2"] = "highlight",
		["DontShowCTCount"] = false,
		["DontShowInfoFrame"] = false,
		["ModelSoundValue"] = "Short",
		["FilterSelfHud"] = true,
		["WarningY"] = 260,
		["FilterInterrupt"] = true,
		["RangeFrameRadarPoint"] = "CENTER",
		["SpecialWarningY"] = 75,
		["DontRestoreRange"] = false,
		["ShortTimerText"] = true,
		["RangeFrameUpdates"] = "Average",
		["AutoCorrectTimer"] = false,
		["WarningX"] = 0,
		["RaidWarningSound"] = "Sound\\Doodad\\BellTollNightElf.ogg",
		["CustomSounds"] = 0,
		["HPFrameMaxEntries"] = 5,
		["SpecialWarningFlashRepeat3"] = true,
		["RoleSpecAlert"] = true,
		["WhisperStats"] = false,
		["VoiceOverSpecW2"] = "DefaultOnly",
		["InfoFrameLines"] = 0,
		["DontPlayPTCountdown"] = false,
		["SpecialWarningFlashAlph5"] = 0.5,
		["HUDColor3"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["HealthFrameWidth"] = 200,
		["WarningIconLeft"] = true,
		["ShowEngageMessage"] = true,
		["RangeFrameLocked"] = false,
		["HPFrameY"] = 50,
		["WarningFontSize"] = 20,
		["HUDAlpha2"] = 0.5,
		["SpecialWarningFlashDura2"] = 0.4,
		["LastRevision"] = 0,
		["HUDTexture4"] = "highlight",
		["SettingsMessageShown"] = true,
		["PGMessageShown"] = false,
		["DontShowFlexMessage"] = false,
		["HUDColor2"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["CountdownVoice"] = "Corsica",
		["DontSetIcons"] = false,
		["BigBrotherAnnounceToRaid"] = false,
		["AutoRespond"] = true,
		["SpecialWarningFlashRepeat4"] = false,
		["SpecialWarningFont"] = "Fonts\\FRIZQT__.TTF",
		["InfoFrameShowSelf"] = false,
		["SpecialWarningFlashRepeat2"] = false,
		["HideBossEmoteFrame"] = true,
		["SpecialWarningFlashRepeat5"] = true,
		["DisableStatusWhisper"] = false,
		["HealthFrameGrowUp"] = false,
		["HUDTexture1"] = "highlight",
		["RangeFrameFrames"] = "radar",
		["DontPlayCountdowns"] = false,
		["ShowBigBrotherOnCombatStart"] = false,
		["SpecialWarningIcon"] = true,
		["HUDAlphaOverride"] = false,
		["SpecialWarningFlashAlph1"] = 0.3,
		["ShowDefeatMessage"] = true,
		["FilterTankSpec"] = true,
		["DontShowRangeFrame"] = false,
		["HUDSize1"] = 5,
		["WarningDuration"] = 4,
		["WarningFontShadow"] = true,
		["DontShowUserTimers"] = false,
		["HUDColorOverride"] = false,
		["DontShowBossTimers"] = false,
		["SpecialWarningFontStyle"] = "THICKOUTLINE",
		["SWarnClassColor"] = true,
		["SpecialWarningFlashCol4"] = {
			1, -- [1]
			0, -- [2]
			1, -- [3]
		},
		["RangeFrameSound1"] = "none",
		["WorldBossNearAlert"] = false,
		["DontShowBossAnnounces"] = false,
		["HUDAlpha3"] = 0.5,
		["SpecialWarningFlashRepeatAmount"] = 2,
		["AutoAcceptFriendInvite"] = false,
		["WarningIconChat"] = true,
		["CountdownVoice3v2"] = "HoTS_R",
		["HideGuildChallengeUpdates"] = true,
		["SpecialWarningSound5"] = "Sound\\Creature\\Loathstare\\Loa_Naxx_Aggro02.ogg",
		["DontSendYells"] = false,
		["ShowPizzaMessage"] = true,
		["RangeFrameSound2"] = "none",
		["HideTooltips"] = false,
		["SpecialWarningFlashAlph4"] = 0.4,
		["SpecialWarningFlashAlph2"] = 0.3,
		["Enabled"] = true,
		["HUDTexture3"] = "highlight",
		["BCTWMessageShown"] = false,
		["SpecialWarningPoint"] = "CENTER",
		["FilterInterruptNoteName"] = false,
		["SpecialWarningSound2"] = "Sound\\Creature\\AlgalonTheObserver\\UR_Algalon_BHole01.ogg",
		["WarningPoint"] = "CENTER",
		["LogOnlyRaidBosses"] = false,
		["StripServerName"] = true,
		["RangeFrameRadarX"] = 100,
		["SpecialWarningDuration"] = 4,
		["HPFrameX"] = -50,
		["LatencyThreshold"] = 250,
		["SpamBlockBossWhispers"] = true,
		["CATATWMessageShown"] = false,
		["ShowFlashFrame"] = true,
	},
}
